import { Permission } from './permissions';

export interface RolePreset {
  name: string;
  description: string;
  isSystem: boolean;
  permissions: string[];
}

/**
 * Initial system roles per PRD section 20.
 * Permissions can be expanded/edited later by administrators.
 */
export const SYSTEM_ROLES: RolePreset[] = [
  {
    name: 'SUPER_ADMIN',
    description: 'Full system access',
    isSystem: true,
    permissions: Object.values(Permission),
  },
  {
    name: 'ADMIN',
    description: 'Manage system and users',
    isSystem: true,
    permissions: [
      Permission.USER_VIEW,
      Permission.USER_CREATE,
      Permission.USER_UPDATE,
      Permission.USER_ASSIGN_ROLE,
      Permission.ROLE_VIEW,
      Permission.ROLE_CREATE,
      Permission.ROLE_UPDATE,
      Permission.PERMISSION_VIEW,
      Permission.CUSTOMER_VIEW,
      Permission.COMPANY_VIEW,
      Permission.CONTACT_CREATE,
      Permission.CONTACT_UPDATE,
      Permission.CONTACT_DELETE,
      Permission.ACTIVITY_VIEW,
      Permission.ACTIVITY_CREATE,
      Permission.TASK_VIEW,
      Permission.TASK_CREATE,
      Permission.TASK_UPDATE,
      Permission.NOTE_VIEW,
      Permission.NOTE_CREATE,
      Permission.SEARCH,
      Permission.LEAD_VIEW,
      Permission.DEAL_VIEW,
      Permission.TOUR_VIEW,
      Permission.DESTINATION_VIEW,
      Permission.DEPARTURE_VIEW,
      Permission.TRAVELER_VIEW,
      Permission.BOOKING_VIEW,
      Permission.PAYMENT_VIEW,
      Permission.INVOICE_VIEW,
      Permission.QUOTE_VIEW,
      Permission.SUPPLIER_VIEW,
      Permission.HOTEL_VIEW,
      Permission.VEHICLE_VIEW,
      Permission.GUIDE_VIEW,
      Permission.DRIVER_VIEW,
      Permission.TRIP_VIEW,
      Permission.CHECKLIST_VIEW,
      Permission.REPORT_VIEW,
      Permission.AUDIT_VIEW,
      Permission.SETTINGS_VIEW,
      Permission.SETTINGS_UPDATE,
      Permission.NOTIFICATION_VIEW,
      Permission.NOTIFICATION_MANAGE,
      Permission.AUTOMATION_VIEW,
      Permission.AUTOMATION_RUN,
    ],
  },
  {
    name: 'MANAGER',
    description: 'View and manage team activity',
    isSystem: true,
    permissions: [
      Permission.CUSTOMER_VIEW,
      Permission.COMPANY_VIEW,
      Permission.ACTIVITY_VIEW,
      Permission.TASK_VIEW,
      Permission.NOTE_VIEW,
      Permission.SEARCH,
      Permission.LEAD_VIEW,
      Permission.LEAD_UPDATE,
      Permission.DEAL_VIEW,
      Permission.DEAL_UPDATE,
      Permission.TOUR_VIEW,
      Permission.TOUR_CREATE,
      Permission.TOUR_UPDATE,
      Permission.TOUR_PUBLISH,
      Permission.DESTINATION_VIEW,
      Permission.DESTINATION_CREATE,
      Permission.DESTINATION_UPDATE,
      Permission.DEPARTURE_VIEW,
      Permission.DEPARTURE_CREATE,
      Permission.DEPARTURE_UPDATE,
      Permission.BOOKING_VIEW,
      Permission.PAYMENT_VIEW,
      Permission.INVOICE_VIEW,
      Permission.QUOTE_VIEW,
      Permission.SUPPLIER_VIEW,
      Permission.HOTEL_VIEW,
      Permission.VEHICLE_VIEW,
      Permission.GUIDE_VIEW,
      Permission.DRIVER_VIEW,
      Permission.TRIP_VIEW,
      Permission.CHECKLIST_VIEW,
      Permission.REPORT_VIEW,
      Permission.OPERATION_VIEW,
      Permission.NOTIFICATION_VIEW,
      Permission.NOTIFICATION_MANAGE,
      Permission.AUTOMATION_VIEW,
      Permission.AUTOMATION_RUN,
    ],
  },
  {
    name: 'SALES_AGENT',
    description: 'Manage leads, customers, deals, quotes and bookings',
    isSystem: true,
    permissions: [
      Permission.CUSTOMER_VIEW,
      Permission.CUSTOMER_CREATE,
      Permission.CUSTOMER_UPDATE,
      Permission.COMPANY_VIEW,
      Permission.COMPANY_CREATE,
      Permission.COMPANY_UPDATE,
      Permission.CONTACT_CREATE,
      Permission.CONTACT_UPDATE,
      Permission.ACTIVITY_VIEW,
      Permission.ACTIVITY_CREATE,
      Permission.TASK_VIEW,
      Permission.TASK_CREATE,
      Permission.TASK_UPDATE,
      Permission.NOTE_VIEW,
      Permission.NOTE_CREATE,
      Permission.SEARCH,
      Permission.LEAD_VIEW,
      Permission.LEAD_CREATE,
      Permission.LEAD_UPDATE,
      Permission.DEAL_VIEW,
      Permission.DEAL_CREATE,
      Permission.DEAL_UPDATE,
      Permission.BOOKING_VIEW,
      Permission.BOOKING_CREATE,
      Permission.BOOKING_UPDATE,
      Permission.QUOTE_VIEW,
      Permission.QUOTE_CREATE,
      Permission.QUOTE_UPDATE,
      Permission.TOUR_VIEW,
      Permission.DESTINATION_VIEW,
      Permission.DEPARTURE_VIEW,
      Permission.TRAVELER_VIEW,
      Permission.TRAVELER_CREATE,
      Permission.TRAVELER_UPDATE,
      Permission.NOTIFICATION_VIEW,
    ],
  },
  {
    name: 'OPERATIONS_STAFF',
    description: 'Manage departures, travelers, hotels, transport, guides and trip operations',
    isSystem: true,
    permissions: [
      Permission.CUSTOMER_VIEW,
      Permission.TOUR_VIEW,
      Permission.DESTINATION_VIEW,
      Permission.DEPARTURE_VIEW,
      Permission.DEPARTURE_CREATE,
      Permission.DEPARTURE_UPDATE,
      Permission.DEPARTURE_DELETE,
      Permission.TRAVELER_VIEW,
      Permission.TRAVELER_CREATE,
      Permission.TRAVELER_UPDATE,
      Permission.TRAVELER_DELETE,
      Permission.BOOKING_VIEW,
      Permission.BOOKING_UPDATE,
      Permission.OPERATION_VIEW,
      Permission.OPERATION_UPDATE,
      Permission.PAYMENT_VIEW,
      Permission.SUPPLIER_VIEW,
      Permission.SUPPLIER_CREATE,
      Permission.SUPPLIER_UPDATE,
      Permission.SUPPLIER_DELETE,
      Permission.HOTEL_VIEW,
      Permission.HOTEL_CREATE,
      Permission.HOTEL_UPDATE,
      Permission.HOTEL_DELETE,
      Permission.VEHICLE_VIEW,
      Permission.VEHICLE_CREATE,
      Permission.VEHICLE_UPDATE,
      Permission.VEHICLE_DELETE,
      Permission.GUIDE_VIEW,
      Permission.GUIDE_CREATE,
      Permission.GUIDE_UPDATE,
      Permission.GUIDE_DELETE,
      Permission.DRIVER_VIEW,
      Permission.DRIVER_CREATE,
      Permission.DRIVER_UPDATE,
      Permission.DRIVER_DELETE,
      Permission.TRIP_VIEW,
      Permission.TRIP_CONFIGURE,
      Permission.CHECKLIST_VIEW,
      Permission.CHECKLIST_CREATE,
      Permission.CHECKLIST_UPDATE,
      Permission.CHECKLIST_COMPLETE,
      Permission.CHECKLIST_DELETE,
      Permission.NOTIFICATION_VIEW,
      Permission.NOTIFICATION_MANAGE,
    ],
  },
  {
    name: 'FINANCE',
    description: 'Manage invoices, payments and financial reports',
    isSystem: true,
    permissions: [
      Permission.CUSTOMER_VIEW,
      Permission.BOOKING_VIEW,
      Permission.PAYMENT_VIEW,
      Permission.PAYMENT_CREATE,
      Permission.PAYMENT_REFUND,
      Permission.INVOICE_VIEW,
      Permission.INVOICE_CREATE,
      Permission.INVOICE_UPDATE,
      Permission.QUOTE_VIEW,
      Permission.REPORT_VIEW,
      Permission.NOTIFICATION_VIEW,
      Permission.NOTIFICATION_MANAGE,
    ],
  },
  {
    name: 'TOUR_GUIDE',
    description: 'Limited mobile access',
    isSystem: true,
    permissions: [
      Permission.CUSTOMER_VIEW,
      Permission.BOOKING_VIEW,
      Permission.OPERATION_VIEW,
      Permission.NOTIFICATION_VIEW,
    ],
  },
  {
    name: 'DRIVER',
    description: 'Very limited mobile access',
    isSystem: true,
    permissions: [Permission.BOOKING_VIEW, Permission.OPERATION_VIEW, Permission.NOTIFICATION_VIEW],
  },
];
